import { Header } from "@/components/Header";
import Toolbar from "@mui/material/Toolbar/Toolbar";
import type { Metadata } from "next";
import "../reset.css";
import ClientThemeProvider from "./ClientThemeProvider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="fr" suppressHydrationWarning>
      <body>
        <ClientThemeProvider>
          <Toolbar />
          <Header />
          <main>{children}</main>
        </ClientThemeProvider>
      </body>
    </html>
  );
}
